spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/ojdb?useSSL=false
    username: ojadmin
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password: 111111
    database: 0

server:
  port: 8095

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:cc/moonkin/microoj/db/mapper/*.xml

jwt:
  secret: 111111
  expiration: 86400000
  long-expiration: 2592000000

long-crypt:
  key: 111111
  radix: 35

micro-oj:
  login:
    max-attempts: 10
    duration: 1800
    forbidden-time: 3600